f[feat] Save account creation status to DataStore on "Continue" butto…
keep-starknet-strange/starknet-phone pull request #124
Opened 2024-10-29 12:35 UTC by Mystic-Nayy

Resolves #109

2024-10-29 17:21 UTC, Johnnysoltani approved these changes

2024-11-02 03:45 UTC, trbutler4 requested changes
Please delete the local.properties file from git, and then add it to the .gitignore file. This shouldnt be committed to version control. My fault, not yours :)

2024-11-02 03:53 UTC, trbutler4 requested changes

2024-11-02 03:53 UTC, trbutler4 commented on wallet_app/app/src/main/java/com/example/walletapp/ui/onboarding/FinalizeAccountCreationScreen.kt
>          ) {
please fix this. 

![image](https://github.com/user-attachments/assets/442bd2da-87d5-4c63-a817-e5bebec33683)

2024-11-05 04:41 UTC, trbutler4 commented
@Mystic-Nayy please take a look at requested changes to get this done for ODHack

2024-11-05 05:41 UTC, Mystic-Nayy commented
> @Mystic-Nayy please take a look at requested changes to get this done for ODHack

I have made the changes you requested for sir

2024-11-05 19:17 UTC, trbutler4 commented
> > @Mystic-Nayy please take a look at requested changes to get this done for ODHack
> 
> I have made the changes you requested for sir

there are conflicts, the app doesnt even run due to syntax errors. Use android studio

2024-12-12 02:53 UTC, closed without merging