Wallet Ui
keep-starknet-strange/starknet-phone pull request #39
Opened 2024-08-11 19:36 UTC by sajalbnl

made 3 screens of wallet

2024-08-11 22:42 UTC, trbutler4 requested changes

2024-08-11 22:42 UTC, trbutler4 commented on wallet_app/android/app/src/main/java/com/example/walletapp/MainActivity.kt
>  package com.example.walletapp
can you refactor to com.snphone.walletapp?

2024-08-12 14:43 UTC, sajalbnl commented
updated dependencies

2024-08-13 04:26 UTC, trbutler4 commented on wallet_app/android/app/src/main/java/com/example/walletapp/MainActivity.kt
>  package com.example.walletapp
will do this later

2024-08-13 04:26 UTC, merged

2024-08-13 04:26 UTC, trbutler4 commented
nice work!