Adding the create starknet account logic for Kotlin
keep-starknet-strange/starknet-phone pull request #76
Opened 2024-09-11 22:17 UTC by Gerson2102

- [#67] issue #
- [X] follows contribution [guide](https://github.com/keep-starknet-strange/starknet-phone/blob/main/CONTRIBUTING.md)
- [ ] code change includes tests
- [ ] breaking change

Adding the create starknet account logic for Kotlin. I have an error currently. I will give more details inside of the PR.

2024-09-11 22:23 UTC, Gerson2102 commented
This is the error, it seems related to the RPC. But I'm not sure:
![image](https://github.com/user-attachments/assets/88305e1e-aab6-4793-b3a8-419e0699e867)

2024-09-12 01:54 UTC, trbutler4 commented
> This is the error, it seems related to the RPC. But I'm not sure: ![image](https://private-user-images.githubusercontent.com/71728860/366651266-88305e1e-aab6-4793-b3a8-419e0699e867.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMDU4MzQsIm5iZiI6MTcyNjEwNTUzNCwicGF0aCI6Ii83MTcyODg2MC8zNjY2NTEyNjYtODgzMDVlMWUtYWFiNi00NzkzLWIzYTgtNDE5ZTA2OTllODY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDAxNDUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNjdjMTkxNzM5MWE4MjlmY2M4ZDJkYjRhZWY1NjFmMGI1NzNmODA5YjJjODkzMGMyM2RjN2I3MWM0ZGE2YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q7fK8g0xHVFtWYI2eGghCKHJf-WsFEHc8uLkDJn7DtU)
> 
> The RPC that I'm using is katana.

Android is blocking http. You can try using a provider like alchemy, which will give you a free https starknet rpc for the time being. Alternatively you can add the katana url as an allowed url by following option 2b in this guide: https://www.geeksforgeeks.org/android-cleartext-http-traffic-not-permitted/

2024-09-12 19:34 UTC, Gerson2102 commented
> > This is the error, it seems related to the RPC. But I'm not sure: ![image](https://private-user-images.githubusercontent.com/71728860/366651266-88305e1e-aab6-4793-b3a8-419e0699e867.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMDU4MzQsIm5iZiI6MTcyNjEwNTUzNCwicGF0aCI6Ii83MTcyODg2MC8zNjY2NTEyNjYtODgzMDVlMWUtYWFiNi00NzkzLWIzYTgtNDE5ZTA2OTllODY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDAxNDUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNjdjMTkxNzM5MWE4MjlmY2M4ZDJkYjRhZWY1NjFmMGI1NzNmODA5YjJjODkzMGMyM2RjN2I3MWM0ZGE2YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q7fK8g0xHVFtWYI2eGghCKHJf-WsFEHc8uLkDJn7DtU)
> > The RPC that I'm using is katana.
> 
> Android is blocking http. You can try using a provider like alchemy, which will give you a free https starknet rpc for the time being. Alternatively you can add the katana url as an allowed url by following option 2b in this guide: https://www.geeksforgeeks.org/android-cleartext-http-traffic-not-permitted/ , or just allow all http traffic with option 1b. However we dont want to commit 1b.

Got it. I already did all that stuff. But still not working. Maybe I should change the RPC, do you have that RPC from Alchemy or how can I get that?

2024-09-12 19:42 UTC, Gerson2102 commented
Now its working:
![image](https://github.com/user-attachments/assets/2293738e-6629-4394-8cf5-51ce655f4729)
I just put a different address, from `0.0.0.0` to `10.0.2.2`.

2024-09-15 00:10 UTC, trbutler4 commented
@Gerson2102 Looks good, can you take a look at the conflicts please?

2024-09-15 17:19 UTC, trbutler4 commented on wallet_app/android/app/build.gradle.kts
> +    implementation("com.swmansion.starknet:starknet:0.12.1@aar"){
this is a duplicate dependency. Either remove this one, or the other dep on line 100

2024-09-15 17:26 UTC, trbutler4 requested changes

2024-09-15 17:26 UTC, trbutler4 commented on wallet_app/android/app/build.gradle.kts
> +    implementation("com.swmansion.starknet:starknet:0.12.1@aar"){
this is a duplicate, either remove this or line 100.

2024-09-15 17:26 UTC, trbutler4 commented
Other than change i requested this is a good start. Will merge once that is addressed

2024-09-15 17:27 UTC, trbutler4 commented
actually i will just merge and then remove it.

2024-09-15 17:27 UTC, merged

2024-09-15 17:30 UTC, Gerson2102 commented
Thanks, yesterday I was deleting that dependency por for a reason I couldn't run the app again. And I was trying again today and same story.